### ISSUE TITLE
Feature Request: Tracker Buttons

### ISSUE THREAD

**Issue by KazyEXE** [I5UCC/VRCThumbParamsOSC#10]
I'd love to be able to assign the buttons on SteamVR trackers to OSC parameters.

Kind of like this:
https://twitter.com/vr_hai/status/1698874278525980680

**Comment by I5UCC** [comment]
Great Idea! I'll take a look on how they are handled over openVR

**Comment by I5UCC** [comment]
This was relatively easy to implement. 
Implemented in [v1.2.0](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v1.2.0)
