### ISSUE TITLE
Finger-button position delay very high on Quest wireless

### ISSUE THREAD

**Issue by spacenavy90** [I5UCC/VRCThumbParamsOSC#14]
Playing VRChat on a Quest 2, using Steam Link wireless streaming over a stable 5Ghz connection directly wired to host PC to minimize any latency on that end. Using all default values with the most recent release.

When using the VRC-ASL Gestures animations (https://github.com/I5UCC/VRC-ASL_Gestures) with the Quest/ThumbParams avatar option I am noticing the latency or delay of the detected finger-button changes aren't taking effect in game for around 5 seconds or more. Very rarely it will be as quick as 2 seconds, but around 5 seconds or longer is about the median time I can tell.

Steps to recreate:
1. Confirm OSC and ASL Gestures enabled
2. Make Victory hand pose with A button thumb position to create "R-hand" sign
3. Change thumb position to B button to create "V-hand" sign
4. Count the time between when the VR 3D model changes from R to V-hand sign

**Comment by qbitzvr** [comment]
This happens occasionally for me too, and when it does, the cpu usage seems abnormally high.

![image](https://github.com/I5UCC/VRCThumbParamsOSC/assets/155925902/dc2515c1-2674-4eef-99a7-566bc6d4c09d)

**Comment by qbitzvr** [comment]
@I5UCC Seems to be an issue with the xinput thread hogging resources. 

https://github.com/I5UCC/VRCThumbParamsOSC/blob/99601e3012dc9385e4271039c5013e01c38d27fa/src/xinput.py#L106

I can look into making this asynchronous

**Comment by I5UCC** [comment]
> @I5UCC Seems to be an issue with the xinput thread hogging resources.
> 
> https://github.com/I5UCC/VRCThumbParamsOSC/blob/99601e3012dc9385e4271039c5013e01c38d27fa/src/xinput.py#L106
> 
> I can look into making this asynchronous

yea we should either have that asynchronous, or at best we somehow poll at the same rate as we set in the settings, I moved the polling to the main thread for now, ill see if i can figure something out to do it similar to how we are currently polling from SteamVR https://github.com/I5UCC/VRCThumbParamsOSC/commit/38e3dff0f7a8af39983979fd6b6c12409934bac4

**Comment by qbitzvr** [comment]
For some reason the [`inputs`](https://github.com/zeth/inputs) library requires a high polling rate to function properly. It may be worth looking for alternatives if we can't find a good fix.

**Comment by I5UCC** [comment]
Maybe one of the game libraries could be helpful here, pygame and pyglet

```
import pygame

pygame.init()
joystick = pygame.joystick.Joystick(0)
joystick.init()

while True:
    for event in pygame.event.get():
        if event.type == pygame.JOYBUTTONDOWN:
            if joystick.get_button(0):
                print("A button was pressed")
```

```
import pyglet

joystick = pyglet.input.get_joysticks()[0]
joystick.open()

@joystick.event
def on_joybutton_press(joystick, button):
    print('Button %s was pressed.' % button)

pyglet.app.run()
```

**Comment by I5UCC** [comment]
https://github.com/r4dian/Xbox-Controller-for-Python/blob/master/xinput.py

This seems pretty promising using pyglet
