### ISSUE TITLE
Option to disable ints and send only bool

### ISSUE THREAD

**Issue by SouljaVR** [I5UCC/VRCThumbParamsOSC#2]
Hi, thank you for making this program - It works really well for me :) I just wanted to ask if an option to disable sending int values would be possible? I am only using bools (specifically left thumbstick) so there is a lot of unnecessary OSC data being sent with my setup. Since I run a lot of OSC senders at once, its important that I only send necessary events or sometimes the OSC pipeline stalls/crashes. Some customisation for what is/isnt sent would be an awesome addition. Thank you so much for this once again @I5UCC :)

**Comment by I5UCC** [comment]
Hey, thanks for opening an issue! 
Yes that is rather easy to setup, i will push out an update for it soon. 
Also yes, more customization would be a great idea, I'll consider having the ability of removing a parameter off of the config.json file without having the program break. Probably gonna be separating the OSC parameters to something like a "OSCparameters.json" file, to not cause people to delete important lines of the config. 
Thanks for bringing this up!

**Comment by I5UCC** [comment]
Implemented both in [v0.3.2](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v.0.3.2)

**Comment by SouljaVR** [comment]
Thank you so much for doing this, its perfect! Much appreciated @I5UCC <3
