### ISSUE TITLE
Thumbstick Click Bool

### ISSUE THREAD

**Issue by Sarniwoop** [I5UCC/VRCThumbParamsOSC#5]
For what I'm trying to make, it would be perfect if I had a bool when you clicked the left/right thumbstick!

**Comment by I5UCC** [comment]
This will be part of the [rewrite](https://github.com/I5UCC/VRCThumbParamsOSC/tree/rewrite) that will release in a few days

**Comment by I5UCC** [comment]
Implemented in [v1.0.0-Beta](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v1.0.0-Beta)
