### ISSUE TITLE
Index grip strength

### ISSUE THREAD

**Issue by Sarniwoop** [I5UCC/VRCThumbParamsOSC#6]
This might be out of scope for this project, but figured I'd post this anyways.

I was telling a friend of mine about this program and he suggested that a float for measuring the grip strength on index controllers would be very neat to have, for like stress toys on your avatar or controlling particle strength on a prop.

A general "isGrabbing" bool for all controller types would be great too.

**Comment by I5UCC** [comment]
Actually, both of them are very much in the scope for this project. Will be implemented relatively fast.

**Comment by I5UCC** [comment]
Implemented in [v1.0.4](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v1.0.4)
