### ISSUE TITLE
Index trackpad pressure sensor

### ISSUE THREAD

**Issue by Greendayle** [I5UCC/VRCThumbParamsOSC#8]
Index trackpads are 3D inputs, but I only see X/Y position of the trackpad, is the pressure sensor mapped to any of the OSC params?

Also, what happens to X/Y position after you stop touching the touchpad?

**Comment by I5UCC** [comment]
The X and Y position do reset to 0.0 when the touchpad is released.
I do not have the pressure sensor mapped no, but thats a great addition, ill add it definitely.
